source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TabPageViewController_Example' do
  pod 'TabPageViewController', :path => '../'
end

target 'TabPageViewController_Tests' do
  pod 'TabPageViewController', :path => '../'

  
end
